/**
 * FORGE Gym Tracker — Pre-loaded Exercise Library
 * ~40 common exercises across push/pull/legs/core/cardio categories.
 * IDs are stable strings (not generated) so they survive app reinstalls.
 */

import type { Exercise } from '@/store/gymTypes';

export const DEFAULT_EXERCISES: Omit<Exercise, 'isCustom'>[] = [
  // ── Push (8) ──────────────────────────────────────────────
  { id: 'ex-bench-press',     name: 'Bench Press',        category: 'push', equipment: 'barbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-incline-db',      name: 'Incline DB Press',   category: 'push', equipment: 'dumbbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-overhead-press',  name: 'Overhead Press',     category: 'push', equipment: 'barbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-dips',            name: 'Dips',               category: 'push', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-push-ups',        name: 'Push-ups',           category: 'push', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-cable-fly',       name: 'Cable Fly',          category: 'push', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-lateral-raise',   name: 'Lateral Raise',      category: 'push', equipment: 'dumbbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },
  { id: 'ex-tricep-pushdown', name: 'Tricep Pushdown',    category: 'push', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg' },

  // ── Pull (8) ──────────────────────────────────────────────
  { id: 'ex-barbell-row',     name: 'Barbell Row',        category: 'pull', equipment: 'barbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-pull-ups',        name: 'Pull-ups',           category: 'pull', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-lat-pulldown',    name: 'Lat Pulldown',       category: 'pull', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-seated-row',      name: 'Seated Cable Row',   category: 'pull', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-face-pull',       name: 'Face Pull',          category: 'pull', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-bicep-curl',      name: 'Bicep Curl',         category: 'pull', equipment: 'dumbbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-hammer-curl',     name: 'Hammer Curl',        category: 'pull', equipment: 'dumbbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },
  { id: 'ex-shrugs',          name: 'Shrugs',             category: 'pull', equipment: 'dumbbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg' },

  // ── Legs (8) ──────────────────────────────────────────────
  { id: 'ex-squat',           name: 'Squat',              category: 'legs', equipment: 'barbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-leg-press',       name: 'Leg Press',          category: 'legs', equipment: 'machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-rdl',             name: 'Romanian Deadlift',  category: 'legs', equipment: 'barbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-leg-extension',   name: 'Leg Extension',      category: 'legs', equipment: 'machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-leg-curl',        name: 'Leg Curl',           category: 'legs', equipment: 'machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-calf-raise',      name: 'Calf Raise',         category: 'legs', equipment: 'machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-lunges',          name: 'Lunges',             category: 'legs', equipment: 'dumbbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },
  { id: 'ex-hip-thrust',      name: 'Hip Thrust',         category: 'legs', equipment: 'barbell', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg' },

  // ── Core (8) ──────────────────────────────────────────────
  { id: 'ex-plank',           name: 'Plank',              category: 'core', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-hanging-leg',     name: 'Hanging Leg Raise',  category: 'core', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-cable-crunch',    name: 'Cable Crunch',       category: 'core', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-russian-twist',   name: 'Russian Twist',      category: 'core', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-ab-wheel',        name: 'Ab Wheel',           category: 'core', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-dead-bug',        name: 'Dead Bug',           category: 'core', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-side-plank',      name: 'Side Plank',         category: 'core', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },
  { id: 'ex-woodchop',        name: 'Woodchop',           category: 'core', equipment: 'cable', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg' },

  // ── Cardio (8) ─────────────────────────────────────────────
  { id: 'ex-treadmill',       name: 'Treadmill Run',      category: 'cardio', equipment: 'cardio machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-rowing',          name: 'Rowing Machine',     category: 'cardio', equipment: 'cardio machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-jump-rope',       name: 'Jump Rope',          category: 'cardio', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-cycling',         name: 'Cycling',            category: 'cardio', equipment: 'cardio machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-stair-climber',   name: 'Stair Climber',      category: 'cardio', equipment: 'cardio machine', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-battle-ropes',    name: 'Battle Ropes',       category: 'cardio', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-burpees',         name: 'Burpees',            category: 'cardio', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
  { id: 'ex-mountain-climb',  name: 'Mountain Climbers',  category: 'cardio', equipment: 'bodyweight', videoUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', thumbnailUrl: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg' },
];
